# production ENV is set by default
SCRAPER_ENV: ${SCRAPER_APP_ENV:prod}

spring:
  profiles:
    active: ${SCRAPER_ENV}
  application:
    name: worker-service

  datasource:
    # On Cloud Run, these are usually provided via Environment Variables
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cloud:
    gcp:
      # Real GCP Project ID
      project-id: ${GCP_PROJECT_ID}
      pubsub:
        enabled: true

gcp:
  pubsub:
    # Matches your scraper-topic name in GCP
    scraper-topic-id: scraper-topic

ktor:
  client:
    # Safe defaults for scraping
    connect-timeout-ms: 10000 # 10 seconds to connect
    request-timeout-ms: 30000 # 60 seconds for the entire request/response
    max-connections: 100

scraper:
  patchright:
    # Production path (Linux/Docker structure)
    path: ${user.dir}/bin/patchright/chrome
  headless: true
  gpu-mode: "--disable-gpu"
  profile-base-path: ${user.dir}/playwright-profile
  bing:
    handle-consent: true # Generally needed in cloud IPs
