dependencies {
	
	def ext = rootProject.ext

    // --- CORE SPRING BOOT ---
    implementation "${ext.springBootWeb}"
    implementation "${ext.springBootValidation}"
    implementation "${ext.springBootSecurity}"
    implementation "${ext.springBootDataJpa}"
    implementation "${ext.springBootRetry}"


    // --- HTTP CLIENT AND SCRAPING ---
    implementation "org.jsoup:jsoup:1.17.2"
    implementation "io.ktor:ktor-client-core:${ext.ktorVersion}"
    implementation "io.ktor:ktor-client-cio:${ext.ktorVersion}"
    implementation "com.google.code.gson:gson:2.10.1"
    implementation "com.microsoft.playwright:playwright:1.57.0"

    // --- TEST DEPENDENCIES ---
    testImplementation "org.awaitility:awaitility-kotlin:4.2.0"
}

// --- Playwright CLI Task ---
// To download required browser binaries, run './gradlew playwright --args="install --with-deps chromium"'
tasks.register('playwright', JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    mainClass = 'com.microsoft.playwright.CLI'
}

tasks.withType(Test).configureEach {
    // Forward the system property from the command line to the test runner
    systemProperty "runLiveScraperTest", System.getProperty("runLiveScraperTest")
}

springBoot {
    mainClass = 'com.scraper.worker.WorkerApplicationKt'
}
