dependencies {

	def ext = rootProject.ext
    
    // --- CORE SPRING BOOT ---
    implementation "org.springframework.boot:spring-boot-starter:${ext.springBootVersion}"
    
    // --- CDC DEBEZIUM EMBEDDED ---
    implementation "io.debezium:debezium-embedded:${ext.debeziumVersion}"
    implementation "io.debezium:debezium-connector-postgres:${ext.debeziumVersion}"
    
    // --- GOOGLE PUBSUB ---
    implementation "com.google.cloud:spring-cloud-gcp-starter-pubsub:3.5.0"

    // --- TEST DEPENDENCIES ---
    testImplementation "org.awaitility:awaitility-kotlin:4.2.0"
}

springBoot {
    mainClass = 'com.scraper.cdc.PublisherApplicationKt'
}
