package com.scraper.worker.integration

import com.scraper.worker.dto.PubSubMessage
import com.scraper.worker.service.BingScraper
import com.scraper.worker.service.ScrapeResult
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.condition.DisabledIfSystemProperty
import org.mockito.ArgumentMatchers.anyString
import org.mockito.Mockito.`when`
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.mock.mockito.MockBean
import org.springframework.boot.test.web.client.TestRestTemplate
import org.springframework.http.HttpStatus
import org.springframework.test.context.ActiveProfiles
import java.util.Base64

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class WorkerLogicIT : BaseWorkerIntegrationTest() {

    @Autowired
    private lateinit var restTemplate: TestRestTemplate

    @MockBean
    private lateinit var bingScraper: BingScraper

    @Test
    fun `should process job from pending to completed via push endpoint`() {
        // 1. Arrange: Insert a pending job into the DB manually
        jdbcTemplate.update("INSERT INTO app_user (firebase_uid, email) VALUES (?, ?)", "user-123", "test@example.com")

        val keyword = "pragmatic testing"
        jdbcTemplate.update(
            "INSERT INTO keyword_search (app_user_id, keyword, status, created_at) VALUES (?, ?, ?::search_status, NOW())",
            "user-123", keyword, "PENDING"
        )

        // Grab the ID generated by Postgres
        val jobId = jdbcTemplate.queryForObject("SELECT id FROM keyword_search WHERE keyword = ?", Long::class.java, keyword)!!

        // 2. Mock: Standard Mockito syntax
        `when`(bingScraper.scrape(anyString())).thenReturn(
            ScrapeResult(linkCount = 10, adCount = 2, fullHtml = "<html>test</html>")
        )

        // 3. Prepare: Simulate Pub/Sub Push Envelope
        val innerPayload = """{"searchId": $jobId, "userId": "user-123", "keyword": "$keyword"}"""
        val encodedData = Base64.getEncoder().encodeToString(innerPayload.toByteArray())

        val pushRequest = PubSubMessage(
            message = PubSubMessage.Message(data = encodedData, messageId = "msg-999")
        )

        // 4. Act: POST to the webhook endpoint
        val response = restTemplate.postForEntity("/pubsub/push", pushRequest, String::class.java)

        // 5. Assert: Immediate response is OK
        assertEquals(HttpStatus.OK, response.statusCode)

        // 6. Assert: Wait for @Async processing to hit the DB
        awaitStatusUpdate(jobId, "COMPLETED")

        // Double check side effects
        val finalLinkCount = jdbcTemplate.queryForObject(
            "SELECT total_links FROM keyword_search WHERE id = ?",
            Int::class.java,
            jobId
        )
        assertEquals(10, finalLinkCount)
    }
}
